### PR TITLE
Added simple autocorrect

### PR DESCRIPTION
**Pull request by zpitroda**
Added simple autocorrect

## Checklist
- [ ] Commit includes responses.py entry that corresponds with function in Toolbox (if applicable)
- [ ] Response tests added to tests/test_response.py (if applicable)
- [ ] Pytest does not throw errors

---
This change is [Reviewable](https://reviewable.io/reviews/puffyboa/virtual-assistant/27)

### CODE REVIEW

**Comment by zpitroda** [comment]
[Autocorrect module on github](https://github.com/phatpiglet/autocorrect)

**Comment by lkellar** [comment]
Well, I like the idea of an autocorrect, but I have a bit of a concern. After viewing the [travis ci test of your change](https://travis-ci.org/puffyboa/virtual-assistant/builds/405555946), it looks like the autocorrect significantly slows down the virtual-assistant's replies. From what I've seen, the virtual-assistant takes about 1.2 seconds to run through the tests, and with the autocorrect, it jumps to about 3.2 seconds. 

Also, I've noticed the autocorrect module you linked to seems to be a quite small repo, and not maintained anymore (last commit in 2016). Is there a chance you could maybe find a better maintained autocorrect module, just so incase we run into errors with the autocorrect, we can get it fixed. 

Also, just a quick tip, I saw you made two different PRs, for two commits that seemed related. If you make a PR, then commit to that same branch the PR is on, it will automatically add that commit to the PR.

**Comment by lkellar** [comment]
Also, in the pr, it doesn't seem like you imported the spell function, just looks like you added the pip module to the requirements in #28

**Comment by lkellar** [comment]
I'm going to close this and #28 for now, but feel free to make changes and reopen it. Thanks :)

**Pull request closed without merging**
